import { createHash } from "crypto";
import { ipcRenderer } from "electron";
import { relative } from "path/posix";
import { readFile } from "fs-extra";
import { watch, FSWatcher } from "chokidar";

import { getLastProjectSaveEndTime, isSavingProject } from "../../../project/save/save";
import { getReloadableAssetType, reloadAsset, ReloadableAssetType } from "../../../tools/assets/reload";

import { Editor } from "../../main";

/**
 * Defines the time, in milliseconds, during which the changes of files are considered to be made by the editor
 * itself after it saved the project or after another window of the editor saved an asset.
 */
const selfWriteGracePeriod = 2000;

/**
 * Defines, for each type of asset another window of the editor saves (node particle system, node material and GUI
 * editors), the name it notifies the change with.
 */
const assetUpdatedTypes: Partial<Record<ReloadableAssetType, string>> = {
	"particle-system": "particle-system",
	material: "material",
	gui: "gui",
	scene: "scene",
};

/**
 * Returns wether or not changes of the given file of the assets folder are ignored: hidden files and caches, files
 * generated by the editor, and the content of packages like scenes, which the editor rewrites each time it saves.
 * @param relativePath defines the path of the file, relative to the assets folder, with forward slashes.
 */
export function isIgnoredAssetPath(relativePath: string): boolean {
	const segments = relativePath.split("/").filter((segment) => segment);

	return segments.some((segment, index) => {
		if (segment.startsWith(".") || segment === "node_modules") {
			return true;
		}

		if (index < segments.length - 1 && (segment.endsWith(".scene") || segment.endsWith(".navmesh"))) {
			return true;
		}

		return index === segments.length - 1 && segment.startsWith("editor-generated_");
	});
}

/**
 * Watches the assets folder of the project while the AI assistant runs: the assets browser shows the files it adds,
 * and the elements of the scene created from an asset it modifies are reloaded.
 */
export class AssistantAssetsWatcher {
	private _watcher: FSWatcher | null = null;

	private _refreshTimeout: ReturnType<typeof setTimeout> | null = null;
	private _reloadTimeouts: Map<string, ReturnType<typeof setTimeout>> = new Map();

	private _hashes: Map<string, string> = new Map();
	private _assetUpdatedTimes: Map<string, number> = new Map();

	private _onAssetUpdated = (_: unknown, type: string): void => {
		this._assetUpdatedTimes.set(type, Date.now());
	};

	/**
	 * Constructor.
	 * @param editor defines the reference to the editor.
	 * @param assetsDirectory defines the absolute path of the assets folder of the project.
	 */
	public constructor(
		public readonly editor: Editor,
		public readonly assetsDirectory: string
	) {}

	/**
	 * Starts watching the assets folder.
	 */
	public start(): void {
		if (this._watcher) {
			return;
		}

		this._watcher = watch(this.assetsDirectory, {
			ignoreInitial: true,
			persistent: false,
			ignored: (path) => {
				const relativePath = relative(this.assetsDirectory, path.replace(/\\/g, "/"));
				return relativePath !== "" && isIgnoredAssetPath(relativePath);
			},
			awaitWriteFinish: {
				stabilityThreshold: 250,
				pollInterval: 50,
			},
		});

		this._watcher.on("all", (event, path) => {
			this._scheduleRefresh();

			if (event === "add" || event === "change") {
				this._scheduleReload(path.replace(/\\/g, "/"));
			}
		});

		this._watcher.on("error", (error) => {
			this.editor.layout.console.error(`AI assistant: failed to watch the assets: ${error instanceof Error ? error.message : String(error)}`);
		});

		ipcRenderer.on("editor:asset-updated", this._onAssetUpdated);
	}

	/**
	 * Stops watching the assets folder.
	 */
	public stop(): void {
		ipcRenderer.off("editor:asset-updated", this._onAssetUpdated);

		this._watcher?.close();
		this._watcher = null;

		if (this._refreshTimeout) {
			clearTimeout(this._refreshTimeout);
			this._refreshTimeout = null;
		}

		this._reloadTimeouts.forEach((timeout) => clearTimeout(timeout));
		this._reloadTimeouts.clear();
	}

	private _scheduleRefresh(): void {
		if (this._refreshTimeout) {
			clearTimeout(this._refreshTimeout);
		}

		this._refreshTimeout = setTimeout(() => {
			this._refreshTimeout = null;
			this.editor.layout.assets.refresh();
		}, 300);
	}

	private _scheduleReload(absolutePath: string): void {
		if (!getReloadableAssetType(absolutePath)) {
			return;
		}

		const timeout = this._reloadTimeouts.get(absolutePath);
		if (timeout) {
			clearTimeout(timeout);
		}

		this._reloadTimeouts.set(
			absolutePath,
			setTimeout(() => {
				this._reloadTimeouts.delete(absolutePath);
				this._reload(absolutePath).catch((e) => {
					this.editor.layout.console.error(`AI assistant: failed to reload ${absolutePath}: ${e instanceof Error ? e.message : String(e)}`);
				});
			}, 150)
		);
	}

	private async _reload(absolutePath: string): Promise<void> {
		let hash: string;
		try {
			hash = createHash("md5")
				.update(await readFile(absolutePath))
				.digest("hex");
		} catch (e) {
			// Removed in the meantime.
			return;
		}

		if (this._hashes.get(absolutePath) === hash) {
			return;
		}

		this._hashes.set(absolutePath, hash);

		if (this._isWrittenByEditor(absolutePath)) {
			return;
		}

		const result = await reloadAsset(this.editor, absolutePath);
		if (result.reloaded) {
			this.editor.layout.console.log(`AI assistant: reloaded ${result.reloaded} element${result.reloaded > 1 ? "s" : ""} of the scene from ${result.path}`);
		}
	}

	/**
	 * Returns wether or not the given file was just written by the editor itself: while or right after saving the
	 * project, or right after another window of the editor saved an asset of the same type and updated the scene.
	 */
	private _isWrittenByEditor(absolutePath: string): boolean {
		const now = Date.now();

		if (isSavingProject() || now - getLastProjectSaveEndTime() < selfWriteGracePeriod) {
			return true;
		}

		const type = getReloadableAssetType(absolutePath);
		const assetUpdatedType = type ? assetUpdatedTypes[type] : undefined;

		return !!assetUpdatedType && now - (this._assetUpdatedTimes.get(assetUpdatedType) ?? 0) < selfWriteGracePeriod;
	}
}
